version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/assets
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: assets
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: assets
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
